defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: tweet_a_lot_development

test:
  <<: *defaults
  database: tweet_a_lot_test

# set these environment variables on your prod server
production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>